### ISSUE TITLE
No changelog entry for 0.2.8

### ISSUE THREAD

**Issue by astraw** [rust-embedded/critical-section#32]
It would be useful if there was a changelog entry for 0.2.8, particularly as this release breaks compilation. (Ideally the new changelog entry for 0.2.8 would specify a remedy for the broken compilation.)

**Comment by Dirbaio** [comment]
There is one at the v0.2.x branch, it didn't get ported to `main`. https://github.com/rust-embedded/critical-section/blob/v0.2.x/CHANGELOG.md#unreleased

tldr for the fix is you have to supply a critical section impl for 1.0, see the README for how. I strongly recommend moving off 0.2.x ASAP though.

**Comment by astraw** [comment]
@Dirbaio thanks!
